GRANT SELECT, INSERT, UPDATE, DELETE ON VUELO TO buenaVida_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON USUARIO TO buenaVida_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON VUELO TO buenaVida_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON USUARIO TO buenaVida_user;
